# Generated by Django 2.1.7 on 2019-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Заблокированный'), (3, 'Неподтвержденная регистрация')], default=3, verbose_name='Статус'),
        ),
    ]
