# Generated by Django 2.1.7 on 2019-11-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191123_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='source',
            field=models.TextField(default=None, verbose_name='Ссылка на источник/первоисточник'),
        ),
    ]
