# Generated by Django 2.1.7 on 2019-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_definition_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
