# Generated by Django 2.1.7 on 2019-11-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191124_1901'),
        ('website', '0005_auto_20191125_0059'),
    ]

    operations = [
    ]
