# Generated by Django 2.1.7 on 2019-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_merge_20191130_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='source',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Ссылка на источник/первоисточник'),
        ),
    ]
