# Generated by Django 2.1.7 on 2019-11-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191130_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='website.CustomUser', verbose_name='Автор'),
        ),
    ]
