# Generated by Django 2.1.7 on 2019-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191130_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='estimate',
            field=models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like')], default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='requestforpublication',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Дата создания запроса'),
        ),
    ]
