# Generated by Django 2.2.7 on 2019-12-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191201_1604'),
        ('website', '0011_auto_20191204_0035'),
    ]

    operations = [
    ]
