# Generated by Django 2.1.7 on 2019-12-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20191220_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новое уведомление'),
        ),
    ]
