# Generated by Django 2.1.7 on 2019-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20191220_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like'), (2, 'Notify update status'), (3, 'Status has updated'), (4, 'Def was checked by admin'), (5, 'Def was rejected by admin'), (6, 'Def was published'), (7, 'Block'), (8, 'Unblock by admin'), (9, 'Unblock (time)'), (10, 'Def was added in favorites by smb'), (11, 'Support respond on the email'), (12, 'Request for publication'), (13, 'Request for update status')], default=0, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='requestforpublication',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса'),
        ),
    ]
