# Generated by Django 2.1.7 on 2019-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20191220_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='requestforpublication',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Дата создания запроса'),
        ),
    ]
