# Generated by Django 2.1.7 on 2019-12-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_auto_20191220_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUpdateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (2, 'Отклонен'), (3, 'Опубликован'), (4, 'Навсегда отклонен')], default=1, verbose_name='Статус обновления уровня профиля')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания запроса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
