# Generated by Django 2.1.7 on 2019-12-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_requestupdatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Ваш вопрос')),
                ('name', models.TextField(default='Аноним', verbose_name='Ваше имя')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('date_creation', models.DateTimeField(verbose_name='Дата')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
            ],
        ),
        migrations.AlterField(
            model_name='requestupdatestatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_status', to='website.CustomUser'),
        ),
    ]
