# Generated by Django 2.1.7 on 2019-12-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20191222_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='website.CustomUser', verbose_name='Ссылка на пользователя'),
        ),
    ]
