# Generated by Django 2.1.7 on 2019-12-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_support_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocking',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная '),
        ),
        migrations.AlterField(
            model_name='blocking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='website.CustomUser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like'), (2, 'Notify update status'), (3, 'Status has updated'), (4, 'Def was checked by admin'), (5, 'Def was rejected by admin'), (6, 'Def was published'), (7, 'Block'), (8, 'Unblock by admin'), (9, 'Unblock (time)'), (10, 'Def was added in favorites by smb'), (11, 'Support respond on the email'), (12, 'Request for publication'), (13, 'Request for update status'), (14, 'New question in support')], default=0, verbose_name='Тип события'),
        ),
    ]
